apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-httproute.yaml
  - custom-servicemonitors.yaml
  - longhorn-servicemonitor.yaml
  - flux-podmonitor.yaml
  - cnpg-alerts.yaml
  - dashboards/hubble-dashboard.yaml
  - dashboards/longhorn-dashboard.yaml
  - dashboards/cilium-agent-dashboard.yaml
  - dashboards/etcd-dashboard.yaml
  - dashboards/performance-cockpit-dashboard.yaml
  - dashboards/app-performance-dashboard.yaml
  - dashboards/loki-logs-dashboard.yaml
  - dashboards/cnpg-dashboard.yaml
  - dashboards/flux-cluster-dashboard.yaml
  - dashboards/flux-control-plane-dashboard.yaml
  - dashboards/flux-logs-dashboard.yaml
  - dashboards/node-exporter-full-dashboard.yaml
