apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-httproute.yaml
  - custom-servicemonitors.yaml
  - dashboards/hubble-dashboard.yaml
  - dashboards/cilium-agent-dashboard.yaml
  - dashboards/etcd-dashboard.yaml
  - dashboards/performance-cockpit-dashboard.yaml
  - dashboards/app-performance-dashboard.yaml
  - dashboards/loki-logs-dashboard.yaml
