apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - minio-secrets.yaml
  - secrets.yaml
  - database.yaml
  - configmap.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - scheduled-backup.yaml
  - ops-restart-role.yaml
  - ops-restart-rolebinding.yaml

