apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botkube-plugins-cache
  namespace: botkube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn # Adjust to your storage class
