apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - minio-secrets.yaml
  - secrets.yaml
  - database.yaml
  - storage-config.yaml
  - storage-data.yaml
  - deployment.yaml
  - configmap.yaml
  - service-http.yaml
  - service-ssh.yaml
  - scheduled-backup.yaml
  - ops-restart-role.yaml
  - ops-restart-rolebinding.yaml
  - ops-cnpg-backup-role.yaml
  - ops-cnpg-backup-rolebinding.yaml

