apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-hermes-webhook
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: alertmanager-hermes-webhook
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: hermes/alertmanager-webhook # Vault path (mount: apps)
        property: token
