# infra/controllers/base/monitoring/grafana-creds-externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: grafana-admin-creds
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: grafana
        property: admin-password
