apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - linkding-db-creds.yaml
  - db.yaml
  - deployment.yaml
  - storage.yaml
  - service.yaml
  - backup.yaml
