apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-restart
subjects:
  - kind: User
    name: ops
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ops-restart
  apiGroup: rbac.authorization.k8s.io
